## traefik.yml
log:
  level: DEBUG
accessLog: {}


entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}
        

providers:
  docker:
    exposedByDefault: false

  redis:
     endpoints:
         - "redis-broker:6379"
  file:
    directory: /dynamic
    filename: traefik_dynamic.yml
    watch: false

# API and dashboard configuration
api:
  insecure: true
  dashboard: true