[tool.poetry]
name = "{{ name }}"
version = "0.1.0"
description = ""
authors = ["{{ user_name }} <{{ user_email }}>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-lsp-server = "^1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
